[package]
name = "inductive_miner"
version = "0.1.0"
edition = "2024"
authors = ["Amirov Agil <agil.amirov@gmail.com>"]
description = "This is the implementation of Inductive Miner framework"
readme = true
repository = "https://github.com/Agil1604/Inductive_miner"
license = "MIT"
keywords = ["process-mining", "process-discovery", "event-log"]
categories = ["science", "algorithms", "data-structures"]

[dependencies]
thiserror = "2.0.21"
quick-xml = "0.42.0"
chrono = { version = "0.4", features = ["serde"] }
z3 = "0.21.1"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
